// <auto-generated />
using System;
using LawTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LawTrack.Migrations
{
    [DbContext(typeof(LawTrackDbContext))]
    partial class LawTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LawTrack.Models.Case", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AssignedUserID")
                        .HasColumnType("int");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyIDDefault")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyIDSecond")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedAmountDefault")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedAmountSecond")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AssignedUserID");

                    b.HasIndex("ClientID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("CurrencyIDDefault");

                    b.HasIndex("CurrencyIDSecond");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("PriorityID");

                    b.HasIndex("StatusID");

                    b.HasIndex("TypeID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("LawTrack.Models.CaseCharge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AmountDefault")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountSecond")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CaseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChargeTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyIDDefault")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyIDSecond")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CaseID");

                    b.HasIndex("ChargeTypeID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("CurrencyIDDefault");

                    b.HasIndex("CurrencyIDSecond");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("CaseCharges");
                });

            modelBuilder.Entity("LawTrack.Models.CaseCourt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CaseID")
                        .HasColumnType("int");

                    b.Property<int>("CourtID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CaseID");

                    b.HasIndex("CourtID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("CaseCourts");
                });

            modelBuilder.Entity("LawTrack.Models.CaseDocument", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CaseID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentTypeID")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CaseID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("DocumentTypeID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("CaseDocuments");
                });

            modelBuilder.Entity("LawTrack.Models.CasePayment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AmountDefault")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountSecond")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CaseID")
                        .HasColumnType("int");

                    b.Property<int?>("ChargeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyIDDefault")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyIDSecond")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentMethodDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethodNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CaseID");

                    b.HasIndex("ChargeID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("CurrencyIDDefault");

                    b.HasIndex("CurrencyIDSecond");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("PaymentMethodID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("CasePayments");
                });

            modelBuilder.Entity("LawTrack.Models.CaseStatus", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("CaseStatuses");
                });

            modelBuilder.Entity("LawTrack.Models.CaseTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("AssignedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedUserID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("CaseID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("PriorityID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TaskRecap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AssignedUserID");

                    b.HasIndex("CaseID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("PriorityID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("CaseTasks");
                });

            modelBuilder.Entity("LawTrack.Models.CaseType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("CaseTypes");
                });

            modelBuilder.Entity("LawTrack.Models.ChargeType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("ChargeTypes");
                });

            modelBuilder.Entity("LawTrack.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("StatusID");

                    b.HasIndex("TypeID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("LawTrack.Models.ClientType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("ClientTypes");
                });

            modelBuilder.Entity("LawTrack.Models.Court", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("LawTrack.Models.CourtSession", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CaseID")
                        .HasColumnType("int");

                    b.Property<int>("CourtID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<int?>("JudgeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextSessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CaseID");

                    b.HasIndex("CourtID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("JudgeID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("CourtSessions");
                });

            modelBuilder.Entity("LawTrack.Models.Currency", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("LawTrack.Models.CurrencyConversion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CurrencyIDFrom")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyIDTo")
                        .HasColumnType("int");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("CurrencyIDFrom");

                    b.HasIndex("CurrencyIDTo");

                    b.ToTable("CurrencyConversions");
                });

            modelBuilder.Entity("LawTrack.Models.DocumentType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("LawTrack.Models.Journal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CaseID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<decimal>("CreditDefault")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CreditSecond")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrencyIDDefault")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyIDSecond")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DebitDefault")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebitSecond")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("ReferenceID")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CaseID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("CurrencyIDDefault");

                    b.HasIndex("CurrencyIDSecond");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("LawTrack.Models.Judge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfficeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("Judges");
                });

            modelBuilder.Entity("LawTrack.Models.ModelStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusIDs")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("ModelStatuses");
                });

            modelBuilder.Entity("LawTrack.Models.Module", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ID");

                    b.HasIndex("StatusID");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("LawTrack.Models.PaymentMethod", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("LawTrack.Models.Permission", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("ActionID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModuleID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("ActionID");

                    b.HasIndex("ModuleID");

                    b.HasIndex("StatusID");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("LawTrack.Models.PermissionAction", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("IsForFeature")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ID");

                    b.HasIndex("StatusID");

                    b.ToTable("PermissionActions");
                });

            modelBuilder.Entity("LawTrack.Models.PermissionValue", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ID");

                    b.HasIndex("StatusID");

                    b.ToTable("PermissionValues");
                });

            modelBuilder.Entity("LawTrack.Models.Priority", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Priorities");
                });

            modelBuilder.Entity("LawTrack.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UpdatedUserID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LawTrack.Models.RolePermission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("PermissionID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PermissionID");

                    b.HasIndex("RoleID");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("LawTrack.Models.Status", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("LawTrack.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("StatusID")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserID")
                        .HasColumnType("int");

                    b.Property<string>("UserTypeID")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ID");

                    b.HasIndex("CreatedUserID");

                    b.HasIndex("DeletedUserID");

                    b.HasIndex("RoleID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UpdatedUserID");

                    b.HasIndex("UserTypeID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LawTrack.Models.UserType", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("LawTrack.Models.Case", b =>
                {
                    b.HasOne("LawTrack.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Currency", "CurrencyDefault")
                        .WithMany()
                        .HasForeignKey("CurrencyIDDefault")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Currency", "CurrencySecond")
                        .WithMany()
                        .HasForeignKey("CurrencyIDSecond")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.CaseStatus", "CaseStatus")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.CaseType", "CaseType")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedUser");

                    b.Navigation("CaseStatus");

                    b.Navigation("CaseType");

                    b.Navigation("Client");

                    b.Navigation("CreatedUser");

                    b.Navigation("CurrencyDefault");

                    b.Navigation("CurrencySecond");

                    b.Navigation("DeletedUser");

                    b.Navigation("Priority");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.CaseCharge", b =>
                {
                    b.HasOne("LawTrack.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.ChargeType", "ChargeType")
                        .WithMany()
                        .HasForeignKey("ChargeTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Currency", "CurrencyDefault")
                        .WithMany()
                        .HasForeignKey("CurrencyIDDefault")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Currency", "CurrencySecond")
                        .WithMany()
                        .HasForeignKey("CurrencyIDSecond")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("ChargeType");

                    b.Navigation("CreatedUser");

                    b.Navigation("CurrencyDefault");

                    b.Navigation("CurrencySecond");

                    b.Navigation("DeletedUser");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.CaseCourt", b =>
                {
                    b.HasOne("LawTrack.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("Court");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.CaseDocument", b =>
                {
                    b.HasOne("LawTrack.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("DocumentType");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.CasePayment", b =>
                {
                    b.HasOne("LawTrack.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.CaseCharge", "Charge")
                        .WithMany()
                        .HasForeignKey("ChargeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Currency", "CurrencyDefault")
                        .WithMany()
                        .HasForeignKey("CurrencyIDDefault")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Currency", "CurrencySecond")
                        .WithMany()
                        .HasForeignKey("CurrencyIDSecond")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("Charge");

                    b.Navigation("CreatedUser");

                    b.Navigation("CurrencyDefault");

                    b.Navigation("CurrencySecond");

                    b.Navigation("DeletedUser");

                    b.Navigation("PaymentMethod");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.CaseTask", b =>
                {
                    b.HasOne("LawTrack.Models.User", "AssignedUserTo")
                        .WithMany()
                        .HasForeignKey("AssignedUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedUserTo");

                    b.Navigation("Case");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Priority");

                    b.Navigation("Status");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.CaseType", b =>
                {
                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Status");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.ChargeType", b =>
                {
                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Status");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.Client", b =>
                {
                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.ClientType", "ClientType")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClientType");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Status");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.ClientType", b =>
                {
                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Status");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.Court", b =>
                {
                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Status");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.CourtSession", b =>
                {
                    b.HasOne("LawTrack.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Judge", "Judge")
                        .WithMany()
                        .HasForeignKey("JudgeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("Court");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Judge");

                    b.Navigation("Status");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.CurrencyConversion", b =>
                {
                    b.HasOne("LawTrack.Models.Currency", "CurrencyFrom")
                        .WithMany()
                        .HasForeignKey("CurrencyIDFrom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Currency", "CurrencyTo")
                        .WithMany()
                        .HasForeignKey("CurrencyIDTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrencyFrom");

                    b.Navigation("CurrencyTo");
                });

            modelBuilder.Entity("LawTrack.Models.DocumentType", b =>
                {
                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Status");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.Journal", b =>
                {
                    b.HasOne("LawTrack.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Currency", "CurrencyDefault")
                        .WithMany()
                        .HasForeignKey("CurrencyIDDefault")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Currency", "CurrencySecond")
                        .WithMany()
                        .HasForeignKey("CurrencyIDSecond")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("CreatedUser");

                    b.Navigation("CurrencyDefault");

                    b.Navigation("CurrencySecond");

                    b.Navigation("DeletedUser");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.Judge", b =>
                {
                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Status");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.Module", b =>
                {
                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LawTrack.Models.Permission", b =>
                {
                    b.HasOne("LawTrack.Models.PermissionAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Module");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LawTrack.Models.PermissionAction", b =>
                {
                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LawTrack.Models.PermissionValue", b =>
                {
                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LawTrack.Models.Role", b =>
                {
                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Status");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("LawTrack.Models.RolePermission", b =>
                {
                    b.HasOne("LawTrack.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LawTrack.Models.User", b =>
                {
                    b.HasOne("LawTrack.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LawTrack.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LawTrack.Models.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Role");

                    b.Navigation("Status");

                    b.Navigation("UpdatedUser");

                    b.Navigation("UserType");
                });
#pragma warning restore 612, 618
        }
    }
}
